apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fileapp-ingress
  namespace: fileapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-tls-secret: "fileapp/client-ca-secret"     # namespace/name
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-err-page: "https://files.example.com/403.html"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
spec:
  tls:
  - hosts:
    - files.example.com
    secretName: tls-secrets
  rules:
  - host: files.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fileapp-svc
            port:
              number: 80
